---
title: omniauth-google-oauth2 で認証時にハマったこと
date: 2016/01/16
basename: 2016/01/16/omniauth-google-oauth2-auth-failure
categories: ["Ruby"]
---

前回に引き続き、こんかいも OmniAuth 関連です。  
omniauth-google\-oauth2 にて、ちょっとハマったことがあるので、メモしておきます。

---

[GitHub - zquestz/omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2)

Google OAuth 2 を使って、外部認証ができる omniauth-google\-oauth2 ですが、

```ruby:Gemfile
gem 'omniauth-google-oauth2'
```

と、入れて、設定を行っていると、

```
E, [2016-01-12T18:01:42.389044 #7107] ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch:
{
  "error" : "redirect_uri_mismatch"
}
```

みたいな感じで、エラーが出力され、認証することができません。

そうなったときは、 `omniauth-oauth2` のバージョンを下げることで解決します。

```ruby:Gemfile
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'omniauth-google-oauth2'
```

[redirect_uri_mismatch · Issue #181 · zquestz/omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2/issues/181#issuecomment-151962137)

なんともつらい。
